export const fontList: [string, number][] = [
  ["Alex Brush", 20],
  ["Bilbo Swash Caps", 20],
  ["Calligraffitti", 20],
  ["Coming Soon", 20],
  ["Give You Glory", 20],
  ["Londrina Outline", 20],
  ["Londrina Shadow", 20],
  ["Architects Daughter", 15],
  ["Bonbon", 15],
  ["Butterfly Kids", 15],
  ["Clicker Script", 15],
  ["Great Vibes", 15],
  ["Griffy", 15],
  ["Happy Monkey", 15],
  ["Indie Flower", 15],
  ["Loved by the King", 15],
  ["Miss Fajardose", 15],
  ["Nothing You Could Do", 15],
  ["The Girl Next Door", 15],
  ["Zeyada", 15],
  ["Mr De Haviland", 12],
  ["Belgrano", 10],
  ["Italianno", 10],
  ["Kranky", 10],
  ["Kristi", 10],
  ["Lovers Quarrel", 10],
  ["Over the Rainbow", 10],
  ["Parisienne", 10],
  ["Sevillana", 10],
  ["Shadows Into Light", 10],
  ["Shadows Into Light Two", 10],
  ["Underdog", 10],
  ["Waiting for the Sunrise", 10],
  ["Abril Fatface", 0],
  ["Aclonica", 0],
  ["Acme", 0],
  ["Advent Pro", 0],
  ["Akronim", 0],
  ["Aladin", 0],
  ["Alegreya", 0],
  ["Alegreya Sans", 0],
  ["Alegreya SC", 0],
  ["Alfa Slab One", 0],
  ["Alice", 0],
  ["Amaranth", 0],
  ["Archivo Black", 0],
  ["Archivo Narrow", 0],
  ["Arimo", 0],
  ["Arvo", 0],
  ["Asap", 0],
  ["Astloch", 0],
  ["Asul", 0],
  ["Averia Libre", 0],
  ["Averia Serif Libre", 0],
  ["Bangers", 0],
  ["Basic", 0],
  ["Berkshire Swash", 0],
  ["Bigshot One", 0],
  ["Black Ops One", 0],
  ["Bowlby One SC", 0],
  ["Brawler", 0],
  ["Bubblegum Sans", 0],
  ["Cabin Condensed", 0],
  ["Caesar Dressing", 0],
  ["Cagliostro", 0],
  ["Capriola", 0],
  ["Carter One", 0],
  ["Changa One", 0],
  ["Chango", 0],
  ["Chelsea Market", 0],
  ["Cherry Cream Soda", 0],
  ["Chewy", 0],
  ["Chicle", 0],
  ["Chivo", 0],
  ["Concert One", 0],
  ["Condiment", 0],
  ["Cookie", 0],
  ["Courgette", 0],
  ["Covered By Your Grace", 0],
  ["Crimson Text", 0],
  ["Dancing Script", 0],
  ["Dhurjati", 0],
  ["Doppio One", 0],
  ["Dosis", 0],
  ["Droid Sans", 0],
  ["Eagle Lake", 0],
  ["Electrolize", 0],
  ["Emilys Candy", 0],
  ["Encode Sans", 0],
  ["Encode Sans Compressed", 0],
  ["Euphoria Script", 0],
  ["Exo", 0],
  ["Exo 2", 0],
  ["Faster One", 0],
  ["Federo", 0],
  ["Finger Paint", 0],
  ["Fjord One", 0],
  ["Fontdiner Swanky", 0],
  ["Freckle Face", 0],
  ["Fruktur", 0],
  ["Gabriela", 0],
  ["Geo", 0],
  ["Germania One", 0],
  ["Gloria Hallelujah", 0],
  ["Goudy Bookletter 1911", 0],
  ["Graduate", 0],
  ["Grand Hotel", 0],
  ["Hanalei Fill", 0],
  ["Henny Penny", 0],
  ["Hind", 0],
  ["IM Fell English SC", 0],
  ["Irish Grover", 0],
  ["Jacques Francois Shadow", 0],
  ["Jolly Lodger", 0],
  ["Josefin Slab", 0],
  ["Joti One", 0],
  ["Judson", 0],
  ["Just Another Hand", 0],
  ["Kalam", 0],
  ["Kameron", 0],
  ["Karma", 0],
  ["Kavoon", 0],
  ["Knewave", 0],
  ["Laila", 0],
  ["Lakki Reddy", 0],
  ["Lato", 0],
  ["Leckerli One", 0],
  ["Ledger", 0],
  ["Lekton", 0],
  ["Lemon One", 0],
  ["Liberation Sans", 0],
  ["Libre Caslon Text", 0],
  ["Life Savers", 0],
  ["Lilita One", 0],
  ["Lily Script One", 0],
  ["Limelight", 0],
  ["Lobster", 0],
  ["Lobster Two", 0],
  ["Londrina Solid", 0],
  ["Lora", 0],
  ["Love Ya Like A Sister", 0],
  ["Luckiest Guy", 0],
  ["Lusitana", 0],
  ["Macondo", 0],
  ["Macondo Swash Caps", 0],
  ["Mako", 0],
  ["Marck Script", 0],
  ["Margarine", 0],
  ["Marko One", 0],
  ["Maven Pro", 0],
  ["McLaren", 0],
  ["MedievalSharp", 0],
  ["Merienda One", 0],
  ["Merriweather", 0],
  ["Mervale Script", 0],
  ["Metal Mania", 0],
  ["Metrophobic", 0],
  ["Milonga", 0],
  ["Miltonian Tattoo", 0],
  ["Molle", 0],
  ["Montez", 0],
  ["Montserrat", 0],
  ["Mystery Quest", 0],
  ["Neucha", 0],
  ["New Rocker", 0],
  ["Niconne", 0],
  ["Nosifer", 0],
  ["Noto Sans Oriya", 0],
  ["Noto Serif", 0],
  ["Nova Square", 0],
  ["Nunito", 0],
  ["Old Standard TT", 0],
  ["Oleo Script", 0],
  ["Oleo Script Swash Caps", 0],
  ["Orbitron", 0],
  ["Oregano", 0],
  ["Orienta", 0],
  ["Original Surfer", 0],
  ["Oswald", 0],
  ["Overlock", 0],
  ["Oxygen", 0],
  ["Pacifico", 0],
  ["Paprika", 0],
  ["Patrick Hand SC", 0],
  ["Paytone One", 0],
  ["Peralta", 0],
  ["Permanent Marker", 0],
  ["Piedra", 0],
  ["Pirata One", 0],
  ["Play", 0],
  ["Playball", 0],
  ["Poetsen One", 0],
  ["Poppins", 0],
  ["Press Start 2P", 0],
  ["Princess Sofia", 0],
  ["PT Mono", 0],
  ["Qwigley", 0],
  ["Racing Sans One", 0],
  ["Raleway", 0],
  ["Rancho", 0],
  ["Ranga", 0],
  ["Ribeye", 0],
  ["Roboto", 0],
  ["Roboto Condensed", 0],
  ["Roboto Slab", 0],
  ["Rochester", 0],
  ["Rock Salt", 0],
  ["Rubik One", 0],
  ["Sail", 0],
  ["Salsa", 0],
  ["Sansita One", 0],
  ["Sarina", 0],
  ["Satisfy", 0],
  ["Schoolbell", 0],
  ["Seaweed Script", 0],
  ["Share", 0],
  ["Six Caps", 0],
  ["Skranji", 0],
  ["Source Sans Pro", 0],
  ["Spicy Rice", 0],
  ["Stardos Stencil", 0],
  ["Stoke", 0],
  ["Syncopate", 0],
  ["Teko", 0],
  ["Terminal Dosis", 0],
  ["Tillana", 0],
  ["Timmana", 0],
  ["Titillium Web", 0],
  ["Ubuntu", 0],
  ["Ultra", 0],
  ["UnifrakturCook", 0],
  ["UnifrakturMaguntia", 0],
  ["Vampiro One", 0],
  ["Vidaloka", 0],
  ["Viga", 0],
  ["Voces", 0],
  ["Volkhov", 0],
  ["Vollkorn", 0],
  ["Voltaire", 0],
  ["Wallpoet", 0],
  ["Wellfleet", 0],
  ["Wendy One", 0],
  ["Yellowtail", 0],
  ["Yesteryear", 0]
];
