export const fontCategories = ["Script", "Display", "Handwriting", "Serif", "Sans-serif"];

export const fontList: [string, number, string][] = [
  ["Alex Brush", 20, "Script"],
  ["Bilbo Swash Caps", 20, "Script"],
  ["Calligraffitti", 20, "Handwriting"],
  ["Coming Soon", 20, "Handwriting"],
  ["Give You Glory", 20, "Handwriting"],
  ["Londrina Outline", 20, "Display"],
  ["Londrina Shadow", 20, "Display"],
  ["Architects Daughter", 15, "Handwriting"],
  ["Bonbon", 15, "Handwriting"],
  ["Butterfly Kids", 15, "Script"],
  ["Clicker Script", 15, "Script"],
  ["Great Vibes", 15, "Script"],
  ["Griffy", 15, "Display"],
  ["Happy Monkey", 15, "Display"],
  ["Indie Flower", 15, "Handwriting"],
  ["Loved by the King", 15, "Handwriting"],
  ["Miss Fajardose", 15, "Script"],
  ["Nothing You Could Do", 15, "Handwriting"],
  ["The Girl Next Door", 15, "Handwriting"],
  ["Zeyada", 15, "Handwriting"],
  ["Mr De Haviland", 12, "Script"],
  ["Belgrano", 10, "Serif"],
  ["Italianno", 10, "Script"],
  ["Kranky", 10, "Display"],
  ["Kristi", 10, "Script"],
  ["Lovers Quarrel", 10, "Script"],
  ["Over the Rainbow", 10, "Handwriting"],
  ["Parisienne", 10, "Script"],
  ["Sevillana", 10, "Display"],
  ["Shadows Into Light", 10, "Handwriting"],
  ["Shadows Into Light Two", 10, "Handwriting"],
  ["Underdog", 10, "Display"],
  ["Waiting for the Sunrise", 10, "Handwriting"],
  ["Abril Fatface", 0, "Display"],
  ["Aclonica", 0, "Sans-serif"],
  ["Acme", 0, "Sans-serif"],
  ["Advent Pro", 0, "Sans-serif"],
  ["Akronim", 0, "Display"],
  ["Aladin", 0, "Display"],
  ["Alegreya", 0, "Serif"],
  ["Alegreya Sans", 0, "Sans-serif"],
  ["Alegreya SC", 0, "Serif"],
  ["Alfa Slab One", 0, "Display"],
  ["Alice", 0, "Serif"],
  ["Amaranth", 0, "Sans-serif"],
  ["Archivo Black", 0, "Sans-serif"],
  ["Archivo Narrow", 0, "Sans-serif"],
  ["Arimo", 0, "Sans-serif"],
  ["Arvo", 0, "Serif"],
  ["Asap", 0, "Sans-serif"],
  ["Astloch", 0, "Display"],
  ["Asul", 0, "Sans-serif"],
  ["Averia Libre", 0, "Display"],
  ["Averia Serif Libre", 0, "Display"],
  ["Bangers", 0, "Display"],
  ["Basic", 0, "Sans-serif"],
  ["Berkshire Swash", 0, "Script"],
  ["Bigshot One", 0, "Display"],
  ["Black Ops One", 0, "Display"],
  ["Bowlby One SC", 0, "Display"],
  ["Brawler", 0, "Serif"],
  ["Bubblegum Sans", 0, "Display"],
  ["Cabin Condensed", 0, "Sans-serif"],
  ["Caesar Dressing", 0, "Display"],
  ["Cagliostro", 0, "Sans-serif"],
  ["Capriola", 0, "Sans-serif"],
  ["Carter One", 0, "Display"],
  ["Changa One", 0, "Display"],
  ["Chango", 0, "Display"],
  ["Chelsea Market", 0, "Display"],
  ["Cherry Cream Soda", 0, "Display"],
  ["Chewy", 0, "Display"],
  ["Chicle", 0, "Display"],
  ["Chivo", 0, "Sans-serif"],
  ["Concert One", 0, "Display"],
  ["Condiment", 0, "Script"],
  ["Cookie", 0, "Script"],
  ["Courgette", 0, "Script"],
  ["Covered By Your Grace", 0, "Handwriting"],
  ["Crimson Text", 0, "Serif"],
  ["Dancing Script", 0, "Script"],
  ["Dhurjati", 0, "Sans-serif"],
  ["Doppio One", 0, "Sans-serif"],
  ["Dosis", 0, "Sans-serif"],
  ["Droid Sans", 0, "Sans-serif"],
  ["Eagle Lake", 0, "Display"],
  ["Electrolize", 0, "Sans-serif"],
  ["Emilys Candy", 0, "Display"],
  ["Encode Sans", 0, "Sans-serif"],
  ["Encode Sans Compressed", 0, "Sans-serif"],
  ["Euphoria Script", 0, "Script"],
  ["Exo", 0, "Sans-serif"],
  ["Exo 2", 0, "Sans-serif"],
  ["Faster One", 0, "Display"],
  ["Federo", 0, "Sans-serif"],
  ["Finger Paint", 0, "Display"],
  ["Fjord One", 0, "Serif"],
  ["Fontdiner Swanky", 0, "Display"],
  ["Freckle Face", 0, "Display"],
  ["Fruktur", 0, "Display"],
  ["Gabriela", 0, "Serif"],
  ["Geo", 0, "Sans-serif"],
  ["Germania One", 0, "Display"],
  ["Gloria Hallelujah", 0, "Handwriting"],
  ["Goudy Bookletter 1911", 0, "Serif"],
  ["Graduate", 0, "Display"],
  ["Grand Hotel", 0, "Script"],
  ["Hanalei Fill", 0, "Display"],
  ["Henny Penny", 0, "Display"],
  ["Hind", 0, "Sans-serif"],
  ["IM Fell English SC", 0, "Serif"],
  ["Irish Grover", 0, "Display"],
  ["Jacques Francois Shadow", 0, "Display"],
  ["Jolly Lodger", 0, "Display"],
  ["Josefin Slab", 0, "Serif"],
  ["Joti One", 0, "Display"],
  ["Judson", 0, "Serif"],
  ["Just Another Hand", 0, "Handwriting"],
  ["Kalam", 0, "Handwriting"],
  ["Kameron", 0, "Serif"],
  ["Karma", 0, "Serif"],
  ["Kavoon", 0, "Display"],
  ["Knewave", 0, "Display"],
  ["Laila", 0, "Serif"],
  ["Lakki Reddy", 0, "Script"],
  ["Lato", 0, "Sans-serif"],
  ["Leckerli One", 0, "Script"],
  ["Ledger", 0, "Serif"],
  ["Lekton", 0, "Sans-serif"],
  ["Lemon One", 0, "Display"],
  ["Liberation Sans", 0, "Sans-serif"],
  ["Libre Caslon Text", 0, "Serif"],
  ["Life Savers", 0, "Display"],
  ["Lilita One", 0, "Display"],
  ["Lily Script One", 0, "Script"],
  ["Limelight", 0, "Display"],
  ["Lobster", 0, "Script"],
  ["Lobster Two", 0, "Script"],
  ["Londrina Solid", 0, "Display"],
  ["Lora", 0, "Serif"],
  ["Love Ya Like A Sister", 0, "Handwriting"],
  ["Luckiest Guy", 0, "Display"],
  ["Lusitana", 0, "Serif"],
  ["Macondo", 0, "Display"],
  ["Macondo Swash Caps", 0, "Display"],
  ["Mako", 0, "Sans-serif"],
  ["Marck Script", 0, "Script"],
  ["Margarine", 0, "Display"],
  ["Marko One", 0, "Serif"],
  ["Maven Pro", 0, "Sans-serif"],
  ["McLaren", 0, "Display"],
  ["MedievalSharp", 0, "Display"],
  ["Merienda One", 0, "Script"],
  ["Merriweather", 0, "Serif"],
  ["Mervale Script", 0, "Script"],
  ["Metal Mania", 0, "Display"],
  ["Metrophobic", 0, "Sans-serif"],
  ["Milonga", 0, "Display"],
  ["Miltonian Tattoo", 0, "Display"],
  ["Molle", 0, "Script"],
  ["Montez", 0, "Script"],
  ["Montserrat", 0, "Sans-serif"],
  ["Mystery Quest", 0, "Display"],
  ["Neucha", 0, "Handwriting"],
  ["New Rocker", 0, "Display"],
  ["Niconne", 0, "Script"],
  ["Nosifer", 0, "Display"],
  ["Noto Sans Oriya", 0, "Sans-serif"],
  ["Noto Serif", 0, "Serif"],
  ["Nova Square", 0, "Display"],
  ["Nunito", 0, "Sans-serif"],
  ["Old Standard TT", 0, "Serif"],
  ["Oleo Script", 0, "Script"],
  ["Oleo Script Swash Caps", 0, "Script"],
  ["Orbitron", 0, "Sans-serif"],
  ["Oregano", 0, "Script"],
  ["Orienta", 0, "Sans-serif"],
  ["Original Surfer", 0, "Display"],
  ["Oswald", 0, "Sans-serif"],
  ["Overlock", 0, "Display"],
  ["Oxygen", 0, "Sans-serif"],
  ["Pacifico", 0, "Script"],
  ["Paprika", 0, "Display"],
  ["Patrick Hand SC", 0, "Handwriting"],
  ["Paytone One", 0, "Sans-serif"],
  ["Peralta", 0, "Display"],
  ["Permanent Marker", 0, "Handwriting"],
  ["Piedra", 0, "Display"],
  ["Pirata One", 0, "Display"],
  ["Play", 0, "Sans-serif"],
  ["Playball", 0, "Script"],
  ["Poetsen One", 0, "Display"],
  ["Poppins", 0, "Sans-serif"],
  ["Press Start 2P", 0, "Display"],
  ["Princess Sofia", 0, "Script"],
  ["PT Mono", 0, "Sans-serif"],
  ["Qwigley", 0, "Script"],
  ["Racing Sans One", 0, "Sans-serif"],
  ["Raleway", 0, "Sans-serif"],
  ["Rancho", 0, "Script"],
  ["Ranga", 0, "Display"],
  ["Ribeye", 0, "Display"],
  ["Roboto", 0, "Sans-serif"],
  ["Roboto Condensed", 0, "Sans-serif"],
  ["Roboto Slab", 0, "Serif"],
  ["Rochester", 0, "Script"],
  ["Rock Salt", 0, "Handwriting"],
  ["Rubik One", 0, "Sans-serif"],
  ["Sail", 0, "Script"],
  ["Salsa", 0, "Display"],
  ["Sansita One", 0, "Display"],
  ["Sarina", 0, "Script"],
  ["Satisfy", 0, "Script"],
  ["Schoolbell", 0, "Handwriting"],
  ["Seaweed Script", 0, "Script"],
  ["Share", 0, "Sans-serif"],
  ["Six Caps", 0, "Sans-serif"],
  ["Skranji", 0, "Display"],
  ["Source Sans Pro", 0, "Sans-serif"],
  ["Spicy Rice", 0, "Display"],
  ["Stardos Stencil", 0, "Display"],
  ["Stoke", 0, "Serif"],
  ["Syncopate", 0, "Sans-serif"],
  ["Teko", 0, "Sans-serif"],
  ["Terminal Dosis", 0, "Sans-serif"],
  ["Tillana", 0, "Handwriting"],
  ["Timmana", 0, "Sans-serif"],
  ["Titillium Web", 0, "Sans-serif"],
  ["Ubuntu", 0, "Sans-serif"],
  ["Ultra", 0, "Display"],
  ["UnifrakturCook", 0, "Display"],
  ["UnifrakturMaguntia", 0, "Display"],
  ["Vampiro One", 0, "Display"],
  ["Vidaloka", 0, "Serif"],
  ["Viga", 0, "Sans-serif"],
  ["Voces", 0, "Sans-serif"],
  ["Volkhov", 0, "Serif"],
  ["Vollkorn", 0, "Serif"],
  ["Voltaire", 0, "Sans-serif"],
  ["Wallpoet", 0, "Display"],
  ["Wellfleet", 0, "Display"],
  ["Wendy One", 0, "Display"],
  ["Yellowtail", 0, "Script"],
  ["Yesteryear", 0, "Script"]
];
